version: "3"
services:
  event-track-graphql-api:
    image: event-track-graphql-api:${VERSION}
    env_file: 
      - build/docker/delivery/api/graphql/env.env
    build:
      context: .
      dockerfile: build/docker/delivery/api/graphql/Dockerfile
      args:
        - SERVER=graphql
    ports:
      - "8079:8079"
    deploy:
      resources:
        limits:
          memory: 2g  # Definindo limite de 2 gigabytes de memória
          
  event-track-rest-api:
    image: event-track-rest-api:${VERSION}
    env_file: 
      - build/docker/delivery/api/rest/env.env
    build:
      context: .
      dockerfile: build/docker/delivery/api/rest/Dockerfile
      args:
        - SERVER=rest
    ports:
      - "8085:8085"
    deploy:
      resources:
        limits:
          memory: 2g  # Definindo limite de 2 gigabytes de memória
